### ISSUE TITLE
"jupyterlab_voyager@0.1.0" is not compatible with the current JupyterLab

### ISSUE THREAD

**Issue by daefresh** [altair-viz/jupyterlab_voyager#26]
I have jupyterlab installed. 
I would like to use voyager. 
I've run `jupyter labextension install jupyterlab_voyager --debug` as specified in the readme.
I get this error: `"jupyterlab_voyager@0.1.0" is not compatible with the current JupyterLab`
How do I get this to work?

**Comment by zzhangjii** [comment]
Hi, thanks for reporting the problem, currently voyager is still under development, so may have version conflicts, could you tell me the version of your jupyterlab? use _jupyter lab --version_

**Comment by daefresh** [comment]
Hi, 
I am running `0.31.8`.
Voyager is killer. I love it. I would super appreciative if you helped me figure out a resolution!
Thanks

**Comment by zzhangjii** [comment]
well, current voyager version in master branch have conflicts, try clone this one:

_git clone git@github.com:zzhangjii/jupyterlab_voyager.git_

then install with a development mod:
_yarn install
jupyter labextension link ._

Try with this new development version first, We will probably update the master branch next week.

**Comment by JamesSample** [comment]
Installing from the development branch, as described above, solves the `jupyterlab_voyager@0.1.0 is not compatible` error, but now I'm running into vega/voyager#767. 

I thought I might be able to solve this by changing [line 40 of `package.json`](https://github.com/zzhangjii/jupyterlab_voyager/blob/master/package.json#L40) to 

    "datavoyager": "v2.0.0-alpha.12",

instead of `v2.0.0-alpha.15`, but when I try this the installation fails with

```
$ npm run build

> jupyterlab_voyager@0.1.0 build C:\Users\JES\Downloads\jupyterlab_voyager
> tsc

src/index.ts(102,5): error TS2322: Type '{ showDataSourceSelector: false; manualSpecificationOnly: true; hideHeader: boolean; hideFooter: ...' is not assignable to type 'VoyagerConfig'.
  Object literal may only specify known properties, and 'hideHeader' does not exist in type 'VoyagerConfig'.
src/index.ts(344,32): error TS2551: Property 'getSpec' does not exist on type 'Voyager'. Did you mean 'setSpec'?
src/index.ts(372,34): error TS2551: Property 'getSpec' does not exist on type 'Voyager'. Did you mean 'setSpec'?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jupyterlab_voyager@0.1.0 build: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyterlab_voyager@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JES\AppData\Roaming\npm-cache\_logs\2018-02-27T09_53_06_351Z-debug.log
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c npm run build
Directory: C:\\Users\\JES\\Downloads\\jupyterlab_voyager
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\JES\\Downloads\\jupyterlab_voyager\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Any suggestions for how to solve this would be greatly appreciated - I think the JupyterLab/Voyager2 combo looks amazing!

I'm currently using Anaconda on Windows 10 with Python 3.6 and JupyterLab 0.31.8, but I've also tried building via the Docker file (which uses Ubuntu) and I get a similar error.

Thanks!

**Comment by zzhangjii** [comment]
Current JupyterLab_Voyager relies heavy on new functions in "v2.0.0-alpha.15", most of which don't exist on "v2.0.0-alpha.12".

We are working on issue 767 right now, hope we can solve it soon.

**Comment by daefresh** [comment]
Thank you!

**Comment by saulshanabrook** [comment]
@zzhangjii I am looking at your master branch now and I am unsure if it includes the functionality of saving a temporary `.vl.json` file when opening from a dataframe. Is this something implemented in it currently? If not, is this the route we still think is best? I'm on gitter chat today if are around to talk.

**Comment by zzhangjii** [comment]
@saulshanabrook  yes, it includes saving temp vl.json file, check index.ts line 241: createNew function;
I will be available on gitter after 4:30 pm today

**Comment by saulshanabrook** [comment]
Ah, I see it now. Thank you!

**Comment by saulshanabrook** [comment]
I opened https://github.com/altair-viz/jupyterlab_voyager/pull/32 to track my progress on getting something functional with the latest voyager.

**Comment by Bamieh** [comment]
Hello 👋  any updates on this? I am getting this error as well.


```
Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab                        Extension       Package
>=1.0.10 <2.0.0                   >=0.3.1 <0.4.0  @jupyterlab/rendermime-interfaces
```

**Comment by jimmywan** [comment]
From [this comment](https://github.com/vega/voyager/issues/767#issuecomment-378003969), sounds like things might be resolved.

**Comment by jimmywan** [comment]
Hmm, ignore my previous comment. I tried doing as they recommended and it still failed.
```
 ---> Running in f4ba50ed3a68
> /opt/conda/bin/npm pack jupyterlab_voyager
jupyterlab_voyager-0.1.0.tgz

Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab                        Extension       Package
>=1.0.10 <2.0.0                   >=0.3.1 <0.4.0  @jupyterlab/rendermime-interfaces
The command '/bin/sh -c jupyter labextension install jupyterlab_voyager' returned a non-zero code: 1
```

**Comment by jasongrout** [comment]
It looks like a new version wasn't ever actually released. @saulshanabrook, @gnestor - I also had someone else asking about running voyager in lab 0.32.1. Any chance a release could be made?

**Comment by zzhangjii** [comment]
Hi, @daefresh  @JamesSample @Bamieh @jimmywan @jasongrout 
The new version with the most recent changes has been updated in this repo, it works well with lab 0.32.1.
Also, @saulshanabrook , can you publish it on npm as well?

**Comment by saulshanabrook** [comment]
@zzhangjii Just published 0.2.0. Could I add you to the NPM repo so you can publish whenever you want? What is your username?

**Comment by jimmywan** [comment]
0.2.0 working for me now. Thx!

**Comment by jasongrout** [comment]
Thanks! I think this issue can be closed now.

**Comment by matheusmota** [comment]
Hi, guys. I've just got the same error.

$ jupyter lab --version
0.33.11

Any chance to make it work? Or only downgrading ?
Thanks

**Comment by WeiZhou2372** [comment]
same here

$ jupyter lab --version
1.2.4
