### ISSUE TITLE
Remove top-level menu

### ISSUE THREAD

**Issue by gnestor** [altair-viz/jupyterlab_voyager#36]
I don't think it makes sense to display a top-level "Voyager" in all contexts. The original top-level menu in lab took this approach (there was a "Console" and "Editor" menu that were visible regardless of whether you were working in a notebook, editor, or terminal) and then it was revised to be more general (with "File", "Edit", and "Kernel" menus) and now all of the sub-menu items change based on context. I think it totally makes sense to use context menus and command palette commands for this extension because they can be made available based on the context. The only issue is that they're invisible to the user, so even though the user is probably aware that the extension is installed, he/she may forget and potentially not use it.

I created a commit to remove the menu bar, do with it what you see fit: c73a90805f10635cd913253e155b811be59c3aaa

**Comment by zzhangjii** [comment]
Hi, @gnestor , thanks for the advice
On planning, I will start the user testing next week, so this top-menu bar serves as an alternative option for user to choose, I will record the user's habits and make a summary. 
The ideal design would probably be put functional buttons(save, saveas, undo, redo...) into something like the tool-bar inside notebook:
![screen shot 2018-04-19 at 12 52 47 pm](https://user-images.githubusercontent.com/11495372/39014984-cb29e400-43d0-11e8-8850-69969afad78e.png)
I'm working on it right now.


And as you mentioned, without the top-menu-bar, voyager-extension is pretty much invisible, plus we do need a place to put voyager-tutorial for users, therefore, I suggest we keep it until the user testing is over.

**Comment by gnestor** [comment]
Oh ya, toolbar could be very nice 👍

**Comment by zzhangjii** [comment]
Note, now the top 'Voyager' menu is gone
the tutorial page goes into 'Help';
the "open in voyager" is combined with file context menu;
the "open vl.json in notebook" is added into the vl.json file context menu;
all save/export and show/hide toolbar are inside the context menu of voyager interface

**Comment by gnestor** [comment]
Thanks @zzhangjii! Much better 👍
