### ISSUE TITLE
Cannot open Vega-Lite file with data url

### ISSUE THREAD

**Issue by kanitw** [altair-viz/jupyterlab_voyager#40]
Step to reproduce:

1. Clone Vega-Lite repository
2. Start jupyter lab in the Vega-Lite code folder
3. Go to `examples/specs` folder 
4. Right click on any example with URL data (not inline data) -> Open with -> Voyager (json)

cc: @felixcodes

**Comment by kanitw** [comment]
Yes, but users wouldn't know that.  I wonder if there is a way to fix this in the plugin.  

Also if you need a config in Voyager to pass in path prefix for data url, let us know!

**Comment by zzhangjii** [comment]
local data url working now
