### ISSUE TITLE
Cannot open .vl.json in Notebook

### ISSUE THREAD

**Issue by ssharif6** [altair-viz/jupyterlab_voyager#43]
When exploring a dataset using Voyager, you can export the state to `untitled.vl.json`. However, if you export multiple states of Voyager, it generates file names with `untitled.vl1.json` that increment with a count. The files that have a number in the `vl.json` file path cannot be opened in a Notebook.

![image](https://user-images.githubusercontent.com/9298611/39664545-9aaafc40-5039-11e8-8974-e42cfe8e90fc.png)

This works fine with a normal `someName.vl.json`, but whenever the file suffix is not `.vl.json`, you can no longer use the `Open vl.json file in Notebook` function.

**Comment by zzhangjii** [comment]
Hi, Shaheen, the filename increment with a count should be like 'untitled1.vl.json' since I defined the new file ext to be vl.json. I tried all the export&save buttons and cannot re-produce this error.
Could you tell me your operations in detail?

**Comment by ssharif6** [comment]
Sure. This is how I reproduce the issue

Specify some view within Voyager, and then click `Export Voyager as vl.json` command.
This creates a file `untitled.vl.json`.

Go back to the Voyager tab, and specify some other view, and then perform the same `Export Voyager as vl.json` command. 
This creates a file `untitled.vl1.json`.


Let me know if you can reproduce!

**Comment by zzhangjii** [comment]
I re-tried those steps, and the files I got are `untitled.vl.json `and `untitled1.vl.json`, so I can't reproduce that problem, 
not sure what happened, but I will double check the code in my git repo

**Comment by zzhangjii** [comment]
Design changed, now jupyterlab_voyager will no longer auto-create those files on disk.
