### ISSUE TITLE
Changes to IDocumentWidget in JupyterLab 0.33 break voyager extension

### ISSUE THREAD

**Issue by timkpaine** [altair-viz/jupyterlab_voyager#54]
relevant docs from [changelog](https://github.com/jupyterlab/jupyterlab/blob/master/CHANGELOG.md)

- Main area widgets like the launcher and console inherit from a common MainAreaWidget class which provides a content area (.content) and a toolbar (.toolbar), consistent focus handling and activation behavior, and a spinner displayed until the given reveal promise is resolved. Document widgets, like the notebook and text editor and other documents opened from the document manager, implement the IDocumentWidget interface (instead of DocumentRegistry.IReadyWidget), which builds on MainAreaWidget and adds a .context attribute for the document context and makes dirty handling consistent. Extension authors may consider inheriting from the MainAreaWidget or DocumentWidget class for consistency. Several effects from these changes are noted below. (#3499, #4453)

**Comment by zzhangjii** [comment]
thanks for the suggestion, with jupyterlab updates to 0.34.8,  this voyager extension now changed to IDocumentWidget interface.
