### ISSUE TITLE
Cannot install the Jupyter Lab extension

### ISSUE THREAD

**Issue by suvayu** [altair-viz/jupyterlab_voyager#62]
When trying to install, I get this:

    $ jupyter labextension install jupyterlab_voyager
    [...]
    jupyterlab_voyager-0.2.0.tgz

    ValueError: This extension does not yet support the current version of JupyterLab.

    Conflicting Dependencies:
    JupyterLab              Extension        Package
    >=0.19.1 <0.20.0        >=0.16.3 <0.17.0 @jupyterlab/application
    >=0.19.1 <0.20.0        >=0.16.4 <0.17.0 @jupyterlab/apputils
    >=0.19.1 <0.20.0        >=0.16.3 <0.17.0 @jupyterlab/console
    >=0.19.1 <0.20.0        >=0.16.3 <0.17.0 @jupyterlab/filebrowser
    >=0.19.1 <0.20.0        0.16.3           @jupyterlab/notebook

While in the requirements file (of the released version, 0.2.0) it says `jupyterlab>=0.32.0`, so I'm not sure what's wrong here.

**Comment by laugh12321** [comment]
I also have this situation.

**Comment by josemarfdc** [comment]
Is this issue on someone's radar?

**Comment by saulshanabrook** [comment]
Yeah this is on my radar. It is on my roadmap to bring this repo up to speed with the latest JupyterLab.

Sorry for all the delays here!

**Comment by saulshanabrook** [comment]
Roadmap being: Sometime in the 1 month - 6 month range.

**Comment by jredding** [comment]
@saulshanabrook  Anything we can do to help you out in bringing this repo up to date? We can spare some cycles if you can provide direction. Thanks for everything you're doing!

**Comment by saulshanabrook** [comment]
@jredding Yeah that would be great! I will put together some next steps.

We could have a call next week to discuss them in more depth, if that works for you. 

I tentatively scheduled one for April 9th @ 2pm. If that doesn't work for you, could you suggest another time that week?

> To join the video meeting, click this link: https://meet.google.com/xyt-wkzd-hzq
> Otherwise, to join by phone, dial +1 513-666-3048 and enter this PIN: 186 948 798#


Anyone else is welcome to come if they would like to listen in or participate.

**Comment by jredding** [comment]
@saulshanabrook  Sounds great. What timezone for a 2pm call? EST? (your profile says you're in Ma.) - if so 2pm would work. 

@playermanny2  has this working in a separate repository and I'd love for him to join as well (We work together). 
 https://github.com/altair-viz/jupyterlab_voyager/issues/56#issuecomment-478301028

**Comment by saulshanabrook** [comment]
That would be great! Yep 2pm EST, forgot to mention that!

**Comment by jredding** [comment]
@saulshanabrook  Great. Looking forward to chatting tomorrow. Thanks for taking the time!

**Comment by saulshanabrook** [comment]
@jredding @playermanny2 @ellisonbg and I had a productive meeting!

@playermanny2 is working on getting https://github.com/altair-viz/jupyterlab_voyager/pull/64 ready to merge, so that we can have this extension working on the latest version of JupyterLab.

**Comment by playermanny2** [comment]
The extension now works with jupyterlab ^0.35.x, considering this closed. Let me know if you have any further issues
